[package]
name = "cannons_matrix_multiplication_algorithm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mpi = { git = "https://github.com/rsmpi/rsmpi.git" }
rand = "0.8.5"
ndarray = "0.15.4"